"""Data engine for the German electricity-market dashboard.

Two backing modes:
- DEMO mode (default): builds an in-memory DuckDB with clearly-labelled
  synthetic German market data generated by demo_data.build_demo_db().
- LIVE mode: attaches a user-supplied on-disk DuckDB file (READ_ONLY) that
  follows the expected wide-format schema (see README).

Both paths expose the same query contract to the routers.
"""
from __future__ import annotations

import json
import logging
import re
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from typing import Any

import duckdb
import pandas as pd

from .config import Settings, is_demo_mode
from . import demo_data

logger = logging.getLogger(__name__)


def _records_from_df(df: pd.DataFrame) -> list[dict]:
    """Convert DuckDB-fetched DataFrame → list[dict] with NaN/NaT → None.

    pandas leaves NaN/NaT as-is in `to_dict(orient="records")`, which
    serialises to non-standard `NaN` and is rejected by FastAPI's
    JSON encoder (allow_nan=False). Sanitise here so every router
    sees a clean, JSON-compliant contract.

    Naive datetime columns are localised to UTC (project convention:
    all timestamps are stored in UTC).
    """
    naive_dt_cols = [
        c for c in df.columns
        if pd.api.types.is_datetime64_any_dtype(df[c]) and df[c].dt.tz is None
    ]
    if naive_dt_cols:
        df = df.assign(**{c: df[c].dt.tz_localize("UTC") for c in naive_dt_cols})
    return df.astype(object).where(pd.notna(df), None).to_dict(orient="records")


class DataEngine:
    """Unified query engine over the German market data.

    In demo mode the on-disk file is ignored and an in-memory synthetic
    DuckDB is built once at startup. In live mode the on-disk file is
    attached read-only.
    """

    def __init__(self, settings: Settings):
        self._settings = settings
        self.demo_mode = is_demo_mode(settings)

        self._conn = duckdb.connect()
        # Sidecar CSVs get their own attached in-memory catalog rather than
        # TEMP tables: TEMP objects are session-local and invisible to the
        # per-call cursors that make concurrent request handling safe.
        self._conn.execute("ATTACH ':memory:' AS sidecars")

        if self.demo_mode:
            demo_data.build_demo_db(settings.demo_start, settings.demo_end, conn=self._conn)
            self._conn.execute("SET TimeZone='UTC'")
            self._conn.execute("SET search_path='main,sidecars'")
            logger.info(
                "Running in DEMO mode — synthetic German market data "
                "(%s → %s) generated in memory.",
                settings.demo_start, settings.demo_end,
            )
        else:
            self._conn.execute(f"ATTACH '{settings.duckdb_path}' AS db (READ_ONLY)")
            self._conn.execute("SET TimeZone='UTC'")
            self._conn.execute("SET search_path='db,sidecars'")
            logger.info("Running in LIVE mode — attached DuckDB at %s", settings.duckdb_path)

        # Discover model artifacts / demo artifacts
        self._model_dir = settings.model_results_dir
        if self.demo_mode:
            # Ensure the clearly-labelled synthetic artifact set exists on disk
            # so the file-backed routers (forecast/scenarios/annual-stats/ML)
            # serve demo data without any proprietary model artifacts.
            self._model_dir = self._model_dir / "demo"
            demo_data.write_demo_artifacts(self._model_dir)
        self._latest_production = self._find_latest_dir("Production_Ensemble_")
        self._forecast_dirs = self._discover_forecasts()
        self._small_files_cache: dict[str, Any] = {}
        self._load_small_files()

        self._eur_usd_registered = self._try_register_eur_usd(settings)
        self._coal_api2_registered = self._try_register_coal_api2(settings)

    _TS_PATTERN = re.compile(r"(\d{8}_\d{6})")

    def _parse_timestamp(self, dirname: str) -> datetime | None:
        m = self._TS_PATTERN.search(dirname)
        if m:
            return datetime.strptime(m.group(1), "%Y%m%d_%H%M%S")
        return None

    def _find_latest_dir(self, prefix: str) -> Path | None:
        if not self._model_dir.is_dir():
            return None
        candidates = []
        for d in self._model_dir.iterdir():
            if d.is_dir() and d.name.startswith(prefix):
                ts = self._parse_timestamp(d.name)
                if ts:
                    candidates.append((ts, d))
        if not candidates:
            return None
        candidates.sort(key=lambda x: x[0], reverse=True)
        return candidates[0][1]

    def _discover_forecasts(self) -> dict[str, Path]:
        if not self._model_dir.is_dir():
            return {}
        scenario_map: dict[str, tuple[datetime, Path]] = {}
        for d in self._model_dir.iterdir():
            if not (d.is_dir() and d.name.startswith("Forecast_")):
                continue
            ts = self._parse_timestamp(d.name)
            if not ts:
                continue
            after_ts = self._TS_PATTERN.sub("", d.name.replace("Forecast_", "", 1))
            scenario_key = after_ts.strip("_ ") or "default"
            if not re.match(r'^v\d+_\w+$', scenario_key):
                continue
            if not list(d.glob("predictions_DA_hourly_*.csv")):
                continue
            existing = scenario_map.get(scenario_key)
            if existing is None or ts > existing[0]:
                scenario_map[scenario_key] = (ts, d)
        return {k: v[1] for k, v in scenario_map.items()}

    def _load_small_files(self):
        if self._latest_production is None:
            return
        prod = self._latest_production
        for name in ["metrics.json", "ensemble_config.json"]:
            path = prod / name
            if path.exists():
                with open(path) as f:
                    self._small_files_cache[name] = json.load(f)
        fl_path = prod / "feature_list.txt"
        if fl_path.exists():
            self._small_files_cache["feature_list"] = fl_path.read_text().strip().split("\n")

    def _try_register_eur_usd(self, settings: Settings) -> bool:
        from glob import glob
        raw = glob(str(settings.eur_usd_path))
        if not raw:
            return False
        csvs = sorted((Path(p) for p in raw), key=lambda p: p.stat().st_mtime)
        csv = str(csvs[-1])
        try:
            self._conn.execute(
                f"""
                CREATE TABLE sidecars.eur_usd AS
                SELECT CAST(datetime_UTC AS DATE) AS date,
                       CAST(USD_per_EUR AS DOUBLE) AS USD_per_EUR
                FROM read_csv_auto('{csv}')
                """
            )
            return True
        except Exception:
            logger.warning("Failed to register EUR/USD sidecar from %s", csv, exc_info=True)
            return False

    @property
    def has_eur_usd(self) -> bool:
        return self._eur_usd_registered

    def _try_register_coal_api2(self, settings: Settings) -> bool:
        from glob import glob
        raw = glob(str(settings.coal_api2_path))
        if not raw:
            return False
        csvs = sorted((Path(p) for p in raw), key=lambda p: p.stat().st_mtime)
        csv = str(csvs[-1])
        try:
            self._conn.execute(
                f"""
                CREATE TABLE sidecars.coal_api2 AS
                SELECT CAST(datetime_UTC AS DATE) AS date,
                       CAST(price_USD_ton AS DOUBLE) AS price_USD_ton
                FROM read_csv_auto('{csv}')
                """
            )
            return True
        except Exception:
            logger.warning("Failed to register Coal API2 sidecar from %s", csv, exc_info=True)
            return False

    @property
    def has_coal_api2(self) -> bool:
        return self._coal_api2_registered

    @property
    def latest_production_model(self) -> Path | None:
        return self._latest_production

    @property
    def available_scenarios(self) -> list[str]:
        if self.demo_mode:
            return [self._demo_scenario_key]
        return sorted(self._forecast_dirs.keys())

    @property
    def _demo_scenario_key(self) -> str:
        return "v1_GridExpansionCentral"

    def forecast_dir(self, scenario: str) -> Path | None:
        return self._forecast_dirs.get(scenario)

    def get_cached(self, key: str) -> Any:
        return self._small_files_cache.get(key)

    @contextmanager
    def _cursor(self):
        cur = self._conn.cursor()
        try:
            cur.execute("SET TimeZone='UTC'")
            yield cur
        finally:
            cur.close()

    def query(self, sql: str, params: list | None = None) -> list[dict]:
        with self._cursor() as cur:
            return _records_from_df(cur.execute(sql, params or []).fetchdf())

    def query_wide(
        self,
        table: str,
        columns: list[str],
        start: str | None = None,
        end_exclusive: str | None = None,
        timestamp_col: str = "timestamp_utc",
    ) -> list[dict]:
        quoted = ", ".join(f'"{c}"' for c in columns)
        where, params = [], []
        if start is not None:
            where.append(f'"{timestamp_col}" >= ?')
            params.append(start)
        if end_exclusive is not None:
            where.append(f'"{timestamp_col}" < ?')
            params.append(end_exclusive)
        where_sql = ("WHERE " + " AND ".join(where)) if where else ""
        sql = f'SELECT "{timestamp_col}", {quoted} FROM {table} {where_sql} ORDER BY "{timestamp_col}"'
        return self.query(sql, params)

    _DATETIME_COL_CANDIDATES: tuple[str, ...] = (
        "Datetime_UTC",
        "datetime_UTC",
        "datetime",
    )

    def query_forecast_file(
        self,
        scenario: str,
        filename_pattern: str,
        start: str | None = None,
        end_exclusive: str | None = None,
        datetime_col: str | tuple[str, ...] | None = None,
    ) -> list[dict]:
        fdir = self.forecast_dir(scenario)
        if fdir is None:
            return []
        feather_matches = list(fdir.glob(f"{filename_pattern}.feather"))
        csv_matches = list(fdir.glob(f"{filename_pattern}.csv"))
        candidates: tuple[str, ...]
        if datetime_col is None:
            candidates = self._DATETIME_COL_CANDIDATES
        elif isinstance(datetime_col, str):
            candidates = (datetime_col, *self._DATETIME_COL_CANDIDATES)
        else:
            candidates = tuple(datetime_col)

        if feather_matches:
            df = pd.read_feather(feather_matches[0])
        elif csv_matches:
            df = pd.read_csv(csv_matches[0])
        else:
            return []

        actual_col = next((c for c in candidates if c in df.columns), None)
        if actual_col is None:
            return []

        where_parts = []
        params = []
        if start:
            where_parts.append(f'"{actual_col}" >= ?')
            params.append(start)
        if end_exclusive:
            where_parts.append(f'"{actual_col}" < ?')
            params.append(end_exclusive)

        where_clause = f"WHERE {' AND '.join(where_parts)}" if where_parts else ""
        sql = f'SELECT * FROM _forecast_src {where_clause} ORDER BY "{actual_col}"'

        with self._cursor() as cur:
            cur.register("_forecast_src", df)
            return _records_from_df(cur.execute(sql, params).fetchdf())

    def close(self):
        self._conn.close()